-- Disable noice.nvim plugin to use standard nvim command line
-- local notice = {
--   "folke/noice.nvim",
--   event = "VeryLazy",
--   opts = {
--     -- Disable command line popup to use standard command line
--     cmdline = {
--       enabled = false,
--     },
--     -- Disable popup menu to use standard completion
--     popupmenu = {
--       enabled = false,
--     },
--     -- Disable notify to use standard notifications
--     notify = {
--       enabled = false,
--     },
--     -- Disable lsp progress to use standard progress
--     lsp = {
--       progress = {
--         enabled = false,
--       },
--     },
--   },
--   dependencies = {
--     -- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
--     "MunifTanjim/nui.nvim",
--     -- OPTIONAL:
--     --   `nvim-notify` is only needed, if you want to use the notification view.
--     --   If not available, we use `mini` as the fallback
--     "rcarriga/nvim-notify",
--     }
-- }

-- return notice

-- Return nil to disable the plugin
return nil
