[tools]
go = "1.27.1"
node = "26"
claude = "latest"
antigravity-cli = "latest"
neovim = "0.12.5"

[tasks.ccupdate]
description = 'Claude Codeを最新版に更新'
run = """
#!/usr/bin/env fish

mise use --global claude@latest
mise prune claude
"""

[tasks.agyupdate]
description = 'Antigravity CLIを最新版に更新'
run = """
#!/usr/bin/env fish

mise use --global antigravity-cli@latest
mise prune antigravity-cli
"""
